/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.framework {
	import org.granite.tide.events.TideContextEvent;
	

	[Name("myComponentObserver")]
	[Bindable]
    public class MyComponentObserver {
    	
    	public var untypedEventWithContext:Boolean = false;
    	public var untypedEventWithArgs:Boolean = false;
    	public var untypedEventArg1:String = null;
    	public var untypedEventArg2:Boolean = false;
    	public var typedEvent:int = 0;
    	
    	
    	[Observer]
    	public function myHandler(event:MyEvent):void {
    		typedEvent++;
    	}
    	
    	[Observer("someEvent2")]
    	public function myHandler2(event:TideContextEvent):void {
    		untypedEventWithContext = true;
    	}
    	
    	[Observer("someEvent3")]
    	public function myHandler3(arg1:String, arg2:Boolean):void {
    		untypedEventWithArgs = true;
    		untypedEventArg1 = arg1;
    		untypedEventArg2 = arg2;
    	}
    }
}
